### ISSUE TITLE
Unable to install Kodi 

### ISSUE THREAD

**Issue by mathieuroche** [Saiyato/volumio-kodi-plugin#5] opened 2017-03-19 21:05 UTC
Hi,

Thanks for your plugin.
I've a problem during the install:
2017-03-19T20:57:18.614Z - info: Install script return the error Error: Command failed: echo volumio | sudo -S sh /data/plugins//miscellanea/Kodi Krypton RC1/install.sh > /tmp/installog
[sudo] password for volumio: sh: 0: Can't open /data/plugins//miscellanea/Kodi
I try with:
volumio-kodi-plugin_jarvis_1.3.0.zip
volumio-kodi-plugin_krypton_rc1_2.1.4.zip
My version of volumio is 2.041.

Any idea ?

Thanks.

**Comment by Saiyato** [comment] 2017-03-20 12:24
Hey Mathieu,

I've just uploaded new versions, can you re-check please?

**Comment by Saiyato** [comment] 2017-03-22 08:22
I have tried different versions of Volumio images, can't reproduce the issue. It's probably fixed in the previous commit.

**Closed as completed by Saiyato** 2017-03-22 08:22 UTC
Labels: bug, Already fixed
